apiVersion: app/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      app: vprodb
    spec:
      containers:
        - name: vprodb
          image: abhishekm89/db:latest
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: dp-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: db-volume
          awsElasticBlockStore:
            volumeID: vol-0e8758ca1b8288234
            fsType: ext4
